# Documentation for the stylelint Linter is available at:
# https://stylelint.io/user-guide/rules

defaultSeverity: warning
extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-sass-guidelines
  - stylelint-config-standard-scss
plugins:
  - stylelint-scss
