#!/usr/bin/env node

const glob = require("glob")
const shell = require('shelljs')
const path = require('path')

const testPackages = (error, packages) => {
  if (error) {
    console.log(`⚠️   Error while globing packages:`)
    console.log(error)
    return
  }

  console.log(`🥕  Packages found:\r\n        ${packages.join('\r\n        ')}\r\n`)

  for (const package of packages) {
    testPackage(package)
  }
}

const testPackage = (package) => {
  console.log(`Running Test for ${package}`)
  shell.cd(package)

  const exitCode = shell.exec('yarn test').code

  if (exitCode !== 0) {
    process.exit(exitCode)
  }

  shell.cd('-')
}

glob("packages/*", testPackages)
